### ISSUE TITLE
Rails

### ISSUE THREAD

**Issue by jphenow** [lgromanowski/letsencrypt-plugin#25]
There are a hand full of empty spots like assets, the application template that appear somewhat unnecessary. I would happy to remove those but that got me thinking, why don't we pull the scope of the gem into lets-encrypt interactions. We could then either have a directory of integrations (starting with Rails) to wire it up to frameworks or the framework integrations could be their own gem?

To me that clarifies testing, and widens the ability for this gem to help people.

**Comment by lgromanowski** [comment]
Sorry for silly question (my RoR knowledge is still quite basic), but by interactions you mean something like ActiveInteractions mentioned in this article: http://taylor.fausak.me/2014/01/23/confidently-manage-business-logic-with-active-interaction/ ?

**Comment by halo** [comment]
Since this issue has the name "Rails", may I chime in that Rails 5 is around the corner and I it would be nice to have [this requirement](https://github.com/lgromanowski/letsencrypt-plugin/blob/f9840aaab201829e07b3c6a50c477515cec7f2f1/letsencrypt_plugin.gemspec#L25) loosened up a bit so that it allows for Rails 5?

* Worst case: Allow people to test letsencrypt in the Rails 5 beta already without forking this gem
* Best case: It already works out of the box :)

Would you accept a PR?

**Comment by halo** [comment]
Well [look at that](https://github.com/lgromanowski/letsencrypt-plugin/commits/rails5) I'm sorry I didn't notice that rails5  branch earlier. Keep up the good work! :)
